### ISSUE TITLE
USER STORY: Recipe rating system

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#14]
As a **User**, I would like to **see which of my recipes are the most popular**, so that **I know which type of recipe to focus my efforts to add**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I have created a recipe
	**When** I look at the recipes that I have created
	**Then** I can see the ratings given by other users
- Acceptance Criteria 2
	**Given** that I have created a recipe
	**When** I go into the recipe record
	**Then** I can see the comments from other users
- Acceptance Criteria 3
	**Given** that I have created a recipe or multiple recipes
	**When** I go to my recipes
	**Then** I can see a summary of all my recipes and their individual average ratings

## Tasks
- [ ] Task 1 -  Develop the ability for logged in users to rate a recipe
- [ ] Task 2 – Develop the ability for the recipe creator user, to see a summary page showing all their own recipes and the rating provided by other users
- [ ] Task 3 – Develop a rating section within the recipe details
