### ISSUE TITLE
USER STORY: Recipe Search - advanced

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#16]
As a **User**, I would like to **be able to search the recipes**, so that **I can find the ones that match my fancy at that point in time**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the website
	**When** I navigate to the site
	**Then** I can access a search function to access related recipes
- Acceptance Criteria 2
	**Given** that I am a user of the website
	**When** I search the recipes
	**Then** the search results show relevant recipes

## Tasks
- [ ] Task 1 – Develop a search field on the homepage and recipe page
- [ ] Task 2 – Develop search functionality for the search form for recipe details
- [ ] Task 3 – Enable the search query to match either recipe name, creator name, or ingredients
