### ISSUE TITLE
USER STORY: Recipe Difficulty

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#18]
As a **User**, I would like **to know how difficult a recipe is before I look at it**, so that **I can avoid the difficult ones**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am a user of the site
	**When** I am browsing through the list of recipes
	**Then** I should be able to identify the difficulty of each recipe without reading all the details
- Acceptance Criteria 2
	**Given** that I am a user of the site
	**When** viewing recipe options 
	**Then** the difficulty indicator should be colour coded so I can easily recognise the difficulty

## Tasks
- [ ] Task 1 – Develop a field for difficulty with the recipe model
- [ ] Task 2 – Include within the recipe overview card the difficulty value
- [ ] Task 3 – Style the difficulty by colour to enable easy recognition
