### ISSUE TITLE
USER STORY: Recipe search by difficulty

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#19]
As a **User**, I would like to **be able to search for recipes based on how difficult they are**, so that ** I can avoid the difficult ones**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an inexperienced user
	**When** I search for recipes
	**Then** I can search via difficulty to only show easy recipes
- Acceptance Criteria 2
	**Given** that I am an experienced user
	**When** I search for upto medium difficulty recipes
	**Then** I receive both easy and medium difficulty options
- Acceptance Criteria 3
	**Given** that I am a very experienced user
	**When** I search for hard recipes only
	**Then** I can receive only the hard recipes in my results

## Tasks
- [ ] Task 1 – Develop a filter mechanism for users to filter the recipe results by difficulty field
- [ ] Task 2 – Develop code to enable the difficulty to be applied upto the value specified
- [ ] Task 3 – Develop code to enable the difficulty filter to be applied only matching the value specified
