### ISSUE TITLE
USER STORY: Early deployment to Heroku

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#3]
As a **Developer**, I want to **deploy the app to Heroku**, so that **I can confirm everything works before development of the site and to enable continuous testing within the production environment**

## Tasks
- [ ] Task 1 – Create a new Heroku App
- [ ] Task 2 – Add the database to the app resources
- [ ] Task 3 – Add the secret key’s to the Heroku config vars
- [ ] Task 4 – Configure the settings.py file to point at the correct env.py file in development, the os in deployment and adjust the database section to point at the correct database url from Heroku.
 - [ ] Task 5 – Add the Cloudinary API details to the env.py file and to the Heroku config vars.
- [ ] Task 6 – Adjust the settings.py file to point at the relevant Cloudinary libraries
