### ISSUE TITLE
USER STORY: Create a User account

### ISSUE THREAD

**Issue by MattBCoding** [MattBCoding/pp4-the-pantry2#5]
As a **User**, I would like **to be able to create an account**, so that **I can create and save recipes**

## Acceptance Criteria
- Acceptance Criteria 1
	**Given** that I am an unregistered user
		And, I am on the user registration page
	**When** I enter my username, email address and password
		And, I click on the register button
	**Then** The system creates me an account 
		And, signs me in
- Acceptance Criteria 2
	**Given** that I have an account
		And, I am signed into the account
	**When** I view a recipe
		And, I can see the save recipe button
        **Then** When I click the save recipe button, it saves the recipe to my saved recipes
- Acceptance Criteria 3
	**Given** that I have an account
		And, I am signed into the account
	**When** I have an option to create a recipe
		And, when I click on that option
	**Then** I am taken to a page where I can provide the details of my recipe
                And, when I click save, the recipe is saved to the database for others to see

## Tasks
- [ ] Task 1 – Develop ability for users to register for a user account
- [ ] Task 2 – Develop ability for users to save specific recipes to their profile
- [ ] Task 3 – Develop the ability for users to create their own recipes
- [ ] Task 4 – Restrict access to the save and create recipe buttons to registered users
- [ ] Task 5 – Develop a redirect for users that are not signed in, so that when they click on the save recipe button, or the create recipe button, it redirects them to the sign up/login page. It will need to remember the recipe they were trying to save if redirected from there.
